name: Shell check

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: FKCCF everyday
        run: |
          echo "Beep boop! shellcheck was triggered..."

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Show status
        run: |
          echo "repo was cloned successfully!"

      - name: Install shellcheck
        uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca

      - name: Lint shell scripts
        run: |
          echo "shellcheck begins..."
          shellcheck ./**/*.sh
          echo "Beep boop! shellcheck finished!"
