name: Shell check

on:
  pull_request:
    branches:
      - '*'

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: FKCCF everyday
        run: |
          echo "Beep boop! shellcheck was triggered..."
          echo "I would say, FKCCF!"

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Show status
        run: |
          echo "repo was cloned successfully!"

      - name: shellcheck
        uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca

      - name: Finish
        run: |
          echo "Beep boop! shellcheck finished!"
          echo "Beep boop! You are able to request a review now."
